name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install check tools
        shell: pwsh
        run: .\scripts\install-check-tools.ps1 -Install

      - name: Check addon
        shell: pwsh
        run: .\scripts\check.ps1
